// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Changed_DataType_To_DateTime_For_Movie_Properties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changed_DataType_To_DateTime_For_Movie_Properties));
        
        string IMigrationMetadata.Id
        {
            get { return "202011191458564_Changed_DataType_To_DateTime_For_Movie_Properties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
